version: '2.4'

x-common-definitions: &common-definitions
  stdin_open: true
  tty: true
  volumes:
    - ${COBALT_SRC:-.}:/code/
    - ./docker/linux/scripts:/scripts
    - ${COBALT_SRC:-.}/out/ccache:/root/ccache
  depends_on:
    - base

services:
  # Define common build container for Linux
  base:
    build:
      args:
        - BASE_OS
      context: ./docker/linux
      dockerfile: base/Dockerfile
    image: cobalt-build-base

  stub:
    <<: *common-definitions
    build:
      context: ./docker/linux
      dockerfile: stub/Dockerfile
    image: cobalt-build-linux-stub
    environment:
      - PLATFORM=stub
      - CONFIG=${CONFIG:-debug}

  linux-x64x11:
    <<: *common-definitions
    build:
      context: ./docker/linux
      dockerfile: linux-x64x11/Dockerfile
    image: cobalt-build-linux
    depends_on: [ build-base ]
    environment:
      - PLATFORM=linux-x64x11
      - CONFIG=${CONFIG:-debug}

<<<<<<< HEAD   (aac228 [PS4] Add 0-byte libSceNpToolkit.prx)
=======
  # Define common build container for Android
  build-android:
    <<: *build-common-definitions
    build:
      context: ./docker/linux/android
      dockerfile: ./Dockerfile
    image: cobalt-build-android

  android-x86:
    <<: *build-common-definitions
    image: cobalt-build-android
    depends_on: [ build-android ]
    environment:
      - IS_DOCKER=1
      - PLATFORM=android-x86
      - CONFIG=${CONFIG:-debug}

  android-arm:
    <<: *build-common-definitions
    image: cobalt-build-android
    depends_on: [ build-android ]
    environment:
      - IS_DOCKER=1
      - PLATFORM=android-arm
      - CONFIG=${CONFIG:-debug}

  android-arm64:
    <<: *build-common-definitions
    image: cobalt-build-android
    depends_on: [ build-android ]
    environment:
      - IS_DOCKER=1
      - PLATFORM=android-arm64
      - CONFIG=${CONFIG:-debug}

  raspi:
    <<: *build-common-definitions
    build:
      context: ./docker/linux/raspi
      dockerfile: ./Dockerfile
    image: cobalt-build-raspi
    environment:
      - PLATFORM
      - CONFIG=${CONFIG:-debug}

>>>>>>> CHANGE (ab57a6 Fixes to docker containers)
  # Define common build container for Evergreen
  build-evergreen:
    <<: *common-definitions
    build:
      context: ./docker/linux
      dockerfile: evergreen/Dockerfile
    image: cobalt-build-evergreen
    environment:
      - PLATFORM
      - CONFIG

  evergreen-x64-sbversion-12:
    <<: *common-definitions
    image: cobalt-build-evergreen
    depends_on: [ build-evergreen ]
    environment:
      - PLATFORM=evergreen-x64-sbversion-12

  evergreen-x86-sbversion-12:
    <<: *common-definitions
    image: cobalt-build-evergreen
    depends_on: [ build-evergreen ]
    environment:
      - PLATFORM=evergreen-x86-sbversion-12

  evergreen-arm64-sbversion-12:
    <<: *common-definitions
    image: cobalt-build-evergreen
    depends_on: [ build-evergreen ]
    environment:
      - PLATFORM=evergreen-arm64-sbversion-12

  evergreen-arm-hardfp-sbversion-12:
    <<: *common-definitions
    image: cobalt-build-evergreen
    depends_on: [ build-evergreen ]
    environment:
      - PLATFORM=evergreen-arm-hardfp-sbversion-12

  evergreen-arm-softfp-sbversion-12:
    <<: *common-definitions
    image: cobalt-build-evergreen
    depends_on: [ build-evergreen ]
    environment:
      - PLATFORM=evergreen-arm-softfp-sbversion-12
