name: lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: pre-commit
        if: ${{ github.event_name == 'pull_request' }}
        uses: ./.github/actions/pre_commit
        with:
          base_ref: ${{ github.event.pull_request.base.sha }}
      - name: pre-commit
        if: ${{ github.event_name != 'pull_request' }}
        uses: ./.github/actions/pre_commit
        with:
          base_ref: ${{ github.event.base_ref }}
